pool:
  vmImage: 'windows-latest'

variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)\.m2\repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'



steps:
  - checkout: self
    clean: 'true'
    fetchDepth: '1'

  - task: Cache@2
    inputs:
      key: 'maven | "$(Agent.OS)"'
      path: $(MAVEN_CACHE_FOLDER)
    displayName: 'Cache Maven local repo'

  - powershell: |
      env:
        OAUTH2TOKEN: $(OAUTH2TOKEN)

  - script: |
      echo ON
      choco install ffmpeg --no-progress
      call refreshenv
      echo ON
      call mvn -version
      call mvn -s settings.xml clean deploy --no-transfer-progress $(MAVEN_OPTS)
      echo OFF
    displayName: 'Deploy to GitHub Maven'
